// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.0
// source: internal/pkg/hashmap/pb/shard.proto

package hashmappb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Uint32List struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Values        []uint32               `protobuf:"varint,1,rep,packed,name=values,proto3" json:"values,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Uint32List) Reset() {
	*x = Uint32List{}
	mi := &file_internal_pkg_hashmap_pb_shard_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Uint32List) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Uint32List) ProtoMessage() {}

func (x *Uint32List) ProtoReflect() protoreflect.Message {
	mi := &file_internal_pkg_hashmap_pb_shard_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Uint32List.ProtoReflect.Descriptor instead.
func (*Uint32List) Descriptor() ([]byte, []int) {
	return file_internal_pkg_hashmap_pb_shard_proto_rawDescGZIP(), []int{0}
}

func (x *Uint32List) GetValues() []uint32 {
	if x != nil {
		return x.Values
	}
	return nil
}

type Uint64List struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Values        []uint64               `protobuf:"varint,1,rep,packed,name=values,proto3" json:"values,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Uint64List) Reset() {
	*x = Uint64List{}
	mi := &file_internal_pkg_hashmap_pb_shard_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Uint64List) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Uint64List) ProtoMessage() {}

func (x *Uint64List) ProtoReflect() protoreflect.Message {
	mi := &file_internal_pkg_hashmap_pb_shard_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Uint64List.ProtoReflect.Descriptor instead.
func (*Uint64List) Descriptor() ([]byte, []int) {
	return file_internal_pkg_hashmap_pb_shard_proto_rawDescGZIP(), []int{1}
}

func (x *Uint64List) GetValues() []uint64 {
	if x != nil {
		return x.Values
	}
	return nil
}

type ShardPayload struct {
	state                    protoimpl.MessageState `protogen:"open.v1"`
	Version                  uint32                 `protobuf:"varint,1,opt,name=version,proto3" json:"version,omitempty"`
	PrefixLengthHex          uint32                 `protobuf:"varint,2,opt,name=prefix_length_hex,json=prefixLengthHex,proto3" json:"prefix_length_hex,omitempty"`
	SuffixLengthBytes        uint32                 `protobuf:"varint,3,opt,name=suffix_length_bytes,json=suffixLengthBytes,proto3" json:"suffix_length_bytes,omitempty"`
	TotalEntries             uint32                 `protobuf:"varint,4,opt,name=total_entries,json=totalEntries,proto3" json:"total_entries,omitempty"`
	FilterSeed               uint64                 `protobuf:"varint,5,opt,name=filter_seed,json=filterSeed,proto3" json:"filter_seed,omitempty"`
	FilterSegmentLength      uint32                 `protobuf:"varint,6,opt,name=filter_segment_length,json=filterSegmentLength,proto3" json:"filter_segment_length,omitempty"`
	FilterSegmentLengthMask  uint32                 `protobuf:"varint,7,opt,name=filter_segment_length_mask,json=filterSegmentLengthMask,proto3" json:"filter_segment_length_mask,omitempty"`
	FilterSegmentCount       uint32                 `protobuf:"varint,8,opt,name=filter_segment_count,json=filterSegmentCount,proto3" json:"filter_segment_count,omitempty"`
	FilterSegmentCountLength uint32                 `protobuf:"varint,9,opt,name=filter_segment_count_length,json=filterSegmentCountLength,proto3" json:"filter_segment_count_length,omitempty"`
	FilterFingerprints       []byte                 `protobuf:"bytes,10,opt,name=filter_fingerprints,json=filterFingerprints,proto3" json:"filter_fingerprints,omitempty"`
	MphValues                []int32                `protobuf:"varint,11,rep,packed,name=mph_values,json=mphValues,proto3" json:"mph_values,omitempty"`
	MphSeeds                 []int32                `protobuf:"varint,12,rep,packed,name=mph_seeds,json=mphSeeds,proto3" json:"mph_seeds,omitempty"`
	// Types that are valid to be assigned to Indices:
	//
	//	*ShardPayload_Indices32
	//	*ShardPayload_Indices64
	Indices       isShardPayload_Indices `protobuf_oneof:"indices"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ShardPayload) Reset() {
	*x = ShardPayload{}
	mi := &file_internal_pkg_hashmap_pb_shard_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShardPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShardPayload) ProtoMessage() {}

func (x *ShardPayload) ProtoReflect() protoreflect.Message {
	mi := &file_internal_pkg_hashmap_pb_shard_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShardPayload.ProtoReflect.Descriptor instead.
func (*ShardPayload) Descriptor() ([]byte, []int) {
	return file_internal_pkg_hashmap_pb_shard_proto_rawDescGZIP(), []int{2}
}

func (x *ShardPayload) GetVersion() uint32 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *ShardPayload) GetPrefixLengthHex() uint32 {
	if x != nil {
		return x.PrefixLengthHex
	}
	return 0
}

func (x *ShardPayload) GetSuffixLengthBytes() uint32 {
	if x != nil {
		return x.SuffixLengthBytes
	}
	return 0
}

func (x *ShardPayload) GetTotalEntries() uint32 {
	if x != nil {
		return x.TotalEntries
	}
	return 0
}

func (x *ShardPayload) GetFilterSeed() uint64 {
	if x != nil {
		return x.FilterSeed
	}
	return 0
}

func (x *ShardPayload) GetFilterSegmentLength() uint32 {
	if x != nil {
		return x.FilterSegmentLength
	}
	return 0
}

func (x *ShardPayload) GetFilterSegmentLengthMask() uint32 {
	if x != nil {
		return x.FilterSegmentLengthMask
	}
	return 0
}

func (x *ShardPayload) GetFilterSegmentCount() uint32 {
	if x != nil {
		return x.FilterSegmentCount
	}
	return 0
}

func (x *ShardPayload) GetFilterSegmentCountLength() uint32 {
	if x != nil {
		return x.FilterSegmentCountLength
	}
	return 0
}

func (x *ShardPayload) GetFilterFingerprints() []byte {
	if x != nil {
		return x.FilterFingerprints
	}
	return nil
}

func (x *ShardPayload) GetMphValues() []int32 {
	if x != nil {
		return x.MphValues
	}
	return nil
}

func (x *ShardPayload) GetMphSeeds() []int32 {
	if x != nil {
		return x.MphSeeds
	}
	return nil
}

func (x *ShardPayload) GetIndices() isShardPayload_Indices {
	if x != nil {
		return x.Indices
	}
	return nil
}

func (x *ShardPayload) GetIndices32() *Uint32List {
	if x != nil {
		if x, ok := x.Indices.(*ShardPayload_Indices32); ok {
			return x.Indices32
		}
	}
	return nil
}

func (x *ShardPayload) GetIndices64() *Uint64List {
	if x != nil {
		if x, ok := x.Indices.(*ShardPayload_Indices64); ok {
			return x.Indices64
		}
	}
	return nil
}

type isShardPayload_Indices interface {
	isShardPayload_Indices()
}

type ShardPayload_Indices32 struct {
	Indices32 *Uint32List `protobuf:"bytes,13,opt,name=indices32,proto3,oneof"`
}

type ShardPayload_Indices64 struct {
	Indices64 *Uint64List `protobuf:"bytes,14,opt,name=indices64,proto3,oneof"`
}

func (*ShardPayload_Indices32) isShardPayload_Indices() {}

func (*ShardPayload_Indices64) isShardPayload_Indices() {}

var File_internal_pkg_hashmap_pb_shard_proto protoreflect.FileDescriptor

const file_internal_pkg_hashmap_pb_shard_proto_rawDesc = "" +
	"\n" +
	"#internal/pkg/hashmap/pb/shard.proto\x12\ramber.hashmap\"$\n" +
	"\n" +
	"Uint32List\x12\x16\n" +
	"\x06values\x18\x01 \x03(\rR\x06values\"$\n" +
	"\n" +
	"Uint64List\x12\x16\n" +
	"\x06values\x18\x01 \x03(\x04R\x06values\"\x9a\x05\n" +
	"\fShardPayload\x12\x18\n" +
	"\aversion\x18\x01 \x01(\rR\aversion\x12*\n" +
	"\x11prefix_length_hex\x18\x02 \x01(\rR\x0fprefixLengthHex\x12.\n" +
	"\x13suffix_length_bytes\x18\x03 \x01(\rR\x11suffixLengthBytes\x12#\n" +
	"\rtotal_entries\x18\x04 \x01(\rR\ftotalEntries\x12\x1f\n" +
	"\vfilter_seed\x18\x05 \x01(\x04R\n" +
	"filterSeed\x122\n" +
	"\x15filter_segment_length\x18\x06 \x01(\rR\x13filterSegmentLength\x12;\n" +
	"\x1afilter_segment_length_mask\x18\a \x01(\rR\x17filterSegmentLengthMask\x120\n" +
	"\x14filter_segment_count\x18\b \x01(\rR\x12filterSegmentCount\x12=\n" +
	"\x1bfilter_segment_count_length\x18\t \x01(\rR\x18filterSegmentCountLength\x12/\n" +
	"\x13filter_fingerprints\x18\n" +
	" \x01(\fR\x12filterFingerprints\x12\x1d\n" +
	"\n" +
	"mph_values\x18\v \x03(\x05R\tmphValues\x12\x1b\n" +
	"\tmph_seeds\x18\f \x03(\x05R\bmphSeeds\x129\n" +
	"\tindices32\x18\r \x01(\v2\x19.amber.hashmap.Uint32ListH\x00R\tindices32\x129\n" +
	"\tindices64\x18\x0e \x01(\v2\x19.amber.hashmap.Uint64ListH\x00R\tindices64B\t\n" +
	"\aindicesB@Z>github.com/bobcallaway/amber/internal/pkg/hashmap/pb;hashmappbb\x06proto3"

var (
	file_internal_pkg_hashmap_pb_shard_proto_rawDescOnce sync.Once
	file_internal_pkg_hashmap_pb_shard_proto_rawDescData []byte
)

func file_internal_pkg_hashmap_pb_shard_proto_rawDescGZIP() []byte {
	file_internal_pkg_hashmap_pb_shard_proto_rawDescOnce.Do(func() {
		file_internal_pkg_hashmap_pb_shard_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_pkg_hashmap_pb_shard_proto_rawDesc), len(file_internal_pkg_hashmap_pb_shard_proto_rawDesc)))
	})
	return file_internal_pkg_hashmap_pb_shard_proto_rawDescData
}

var file_internal_pkg_hashmap_pb_shard_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_internal_pkg_hashmap_pb_shard_proto_goTypes = []any{
	(*Uint32List)(nil),   // 0: amber.hashmap.Uint32List
	(*Uint64List)(nil),   // 1: amber.hashmap.Uint64List
	(*ShardPayload)(nil), // 2: amber.hashmap.ShardPayload
}
var file_internal_pkg_hashmap_pb_shard_proto_depIdxs = []int32{
	0, // 0: amber.hashmap.ShardPayload.indices32:type_name -> amber.hashmap.Uint32List
	1, // 1: amber.hashmap.ShardPayload.indices64:type_name -> amber.hashmap.Uint64List
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_internal_pkg_hashmap_pb_shard_proto_init() }
func file_internal_pkg_hashmap_pb_shard_proto_init() {
	if File_internal_pkg_hashmap_pb_shard_proto != nil {
		return
	}
	file_internal_pkg_hashmap_pb_shard_proto_msgTypes[2].OneofWrappers = []any{
		(*ShardPayload_Indices32)(nil),
		(*ShardPayload_Indices64)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_pkg_hashmap_pb_shard_proto_rawDesc), len(file_internal_pkg_hashmap_pb_shard_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_internal_pkg_hashmap_pb_shard_proto_goTypes,
		DependencyIndexes: file_internal_pkg_hashmap_pb_shard_proto_depIdxs,
		MessageInfos:      file_internal_pkg_hashmap_pb_shard_proto_msgTypes,
	}.Build()
	File_internal_pkg_hashmap_pb_shard_proto = out.File
	file_internal_pkg_hashmap_pb_shard_proto_goTypes = nil
	file_internal_pkg_hashmap_pb_shard_proto_depIdxs = nil
}
